fix datepicker problem after click live button
Azure/video-analyzer-widgets pull request #21
Opened 2021-09-14 22:10 UTC by sxian0613

datepicker shows correct date(last day) after clicking the live button

2021-09-16 00:47 UTC, giakas requested changes

2021-09-16 21:48 UTC, sxian0613 commented on packages/web-components/src/player-component/player-component.ts
> +            this.currentDay = parseFloat(this.currentAllowedDays[this.currentAllowedDays.length - 1]);
This part is changed now. This will happen regardless of live or not now.

2021-09-22 00:48 UTC, duggaraju submitted a review, later dismissed

2021-09-27 19:44 UTC, sxian0613 commented
add overflow menu for meta data
1. Removed the meta data button and replaced it with an overflow menu.
2. Added "Bounding Box" and "Attributes" with two checkboxes.
3. Added "confidence" and "speed" to the Attributes showing on the bounding boxes.
4. Controlled the showing of bounding boxes and Attributes by checking the checkboxes.
5. Cleaned the code.

2021-10-07 18:23 UTC, closed without merging